### ISSUE TITLE
remove_chat_roomsでのエラー

### ISSUE THREAD

**Issue by T-M05** [qvco/yaylib#4]
指定した**room_idを削除**しようとするとエラーが出る
```
実行した関数
remove_chat_rooms
```
```
エラー内容
ERROR - Request failed with status code 500. Retrying...
NoneType: None
```

**Comment by qvco** [comment]
不具合の報告ありがとうございます。
修正出来たと思うので、以下のコマンドからパッケージをアップデートして試してみてください。

```bash
py -m pip install -U yaylib
```

**Comment by ekkx** [comment]
> 指定した**room_idを削除**しようとするとエラーが出る
> 
> ```
> 実行した関数
> remove_chat_rooms
> ```
> 
> ```
> エラー内容
> ERROR - Request failed with status code 500. Retrying...
> NoneType: None
> ```

不具合の報告ありがとうございます。
修正出来たと思うので、以下のコマンドからパッケージをアップデートして試してみてください。

```bash
py -m pip install -U yaylib
```

**Comment by T-M05** [comment]
不具合の修正確認できました。
ありがとうございます

**Comment by T-M05** [comment]
> > 指定した**room_idを削除**しようとするとエラーが出る
> > ```
> > 実行した関数
> > remove_chat_rooms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > エラー内容
> > ERROR - Request failed with status code 500. Retrying...
> > NoneType: None
> > ```
> 
> 不具合の報告ありがとうございます。 修正出来たと思うので、以下のコマンドからパッケージをアップデートして試してみてください。
> 
> ```shell
> py -m pip install -U yaylib
> ```

不具合の修正確認できました。
ありがとうございます
