### ISSUE TITLE
reduce_kenta_penaltyでのエラー

### ISSUE THREAD

**Issue by T-M05** [qvco/yaylib#5]
reduce_kenta_penaltyを実行した時にエラーが出る
```
実行した関数
reduce_kenta_penalty
```
```
エラー内容
[Errno 11001] getaddrinfo failed
```

**Comment by ekkx** [comment]
> reduce_kenta_penaltyを実行した時にエラーが出る
> 
> ```
> 
> 実行した関数
> 
> reduce_kenta_penalty
> 
> ```
> 
> ```
> 
> エラー内容
> 
> [Errno 11001] getaddrinfo failed
> 
> ```

報告ありがとうございます。
確認します。

**Comment by ekkx** [comment]
Yay!の運営に不適切な関数だと判断したので、削除することにしました。
ご不便をおかけしますが、ご理解いただけると幸いです。
